import type { DemoIncident, Severity } from "@/lib/types";

export const DEMO_INCIDENTS: DemoIncident[] = [
  {
    incident_id: "demo-wildfire-hillside",
    incident_type: "fire",
    title: "Wildfire smoke plume near hillside homes",
    summary: "Residents report active smoke movement across a residential slope with narrowing access roads.",
    severity: "high",
    priority: "P1",
    analysis_provider: "rule_based_fallback",
    life_safety_risk: false,
    detected_risks: ["fire spread", "smoke exposure"],
    evidence_summary: "Reported fire or smoke conditions with potential spread toward occupied areas.",
    analysis_admin_notes: "Verify fire spread and evaluate evacuation constraints.",
    location: {
      lat: 33.7455,
      lng: -117.8677,
      label: "Hillside neighborhood, Santa Ana demo zone",
      source: "text_location",
      confidence: 0.6,
    },
    evidence: {
      image: {
        filename: "wildfire-plume.jpg",
        content_type: "image/jpeg",
        size_bytes: 248000,
        exif_gps_found: false,
      },
      audio: {
        filename: null,
        content_type: null,
        size_bytes: null,
        transcript: null,
        status: null,
      },
      text: {
        report_text: "Smoke moving across homes near the hillside.",
        location_text: "Santa Ana hillside neighborhood",
      },
    },
    evidence_findings: [
      "Rule-based fallback analysis matched smoke or fire indicators.",
      "Human review is required before dispatching external resources.",
    ],
    recommended_resources: ["Wildfire suppression unit", "Evacuation coordination support", "Air quality monitoring"],
    confidence: 0.84,
    human_review_required: true,
    safety_note: "Decision support only. Not connected to emergency services.",
    updated_at: "2026-05-09T10:15:00Z",
    evidence_count: 3,
  },
  {
    incident_id: "demo-flood-roadway",
    incident_type: "flood",
    title: "Flooded roadway blocking neighborhood access",
    summary: "Road surface is submerged and vehicle access is restricted along the main connector route.",
    severity: "high",
    priority: "P1",
    analysis_provider: "rule_based_fallback",
    life_safety_risk: false,
    detected_risks: ["rising flood water", "blocked roadway access"],
    evidence_summary: "Flooding is affecting road access and nearby structures, with conditions worsening.",
    analysis_admin_notes: "Verify water rise rate and access routes before field deployment.",
    location: {
      lat: 33.7542,
      lng: -117.8549,
      label: "Main connector road, Santa Ana demo zone",
      source: "text_location",
      confidence: 0.6,
    },
    evidence: {
      image: {
        filename: "flooded-road.jpg",
        content_type: "image/jpeg",
        size_bytes: 214000,
        exif_gps_found: false,
      },
      audio: {
        filename: null,
        content_type: null,
        size_bytes: null,
        transcript: null,
        status: null,
      },
      text: {
        report_text: "Flooded access road with stranded vehicles.",
        location_text: "Santa Ana access road",
      },
    },
    evidence_findings: [
      "Rule-based fallback analysis matched flood or water-impact indicators.",
      "Access and safety conditions should be validated by a human operator.",
    ],
    recommended_resources: ["Flood response crew", "Water rescue vehicle", "Road access control"],
    confidence: 0.82,
    human_review_required: true,
    safety_note: "Decision support only. Not connected to emergency services.",
    updated_at: "2026-05-09T10:18:00Z",
    evidence_count: 2,
  },
  {
    incident_id: "demo-medical-assist",
    incident_type: "rescue_medical",
    title: "Medical assistance request at community shelter",
    summary: "Shelter staff report an injured evacuee requiring stabilization and transfer coordination.",
    severity: "critical",
    priority: "P0",
    analysis_provider: "rule_based_fallback",
    life_safety_risk: true,
    detected_risks: ["medical distress", "possible evacuation delay"],
    evidence_summary: "Evidence suggests an immediate rescue or medical life-safety event.",
    analysis_admin_notes: "Prioritize welfare verification and medical escalation.",
    location: {
      lat: 33.7511,
      lng: -117.8714,
      label: "Community shelter, Santa Ana demo zone",
      source: "text_location",
      confidence: 0.6,
    },
    evidence: {
      image: {
        filename: null,
        content_type: null,
        size_bytes: null,
        exif_gps_found: false,
      },
      audio: {
        filename: "shelter-radio.wav",
        content_type: "audio/wav",
        size_bytes: 88000,
        transcript: null,
        status: "received_not_transcribed",
      },
      text: {
        report_text: "Injured evacuee needs medical help.",
        location_text: "Santa Ana community shelter",
      },
    },
    evidence_findings: [
      "Rule-based fallback analysis matched rescue or medical distress language.",
      "Potential life-safety impact requires immediate operator review.",
    ],
    recommended_resources: ["Ambulance or medical team", "Rescue extraction support", "Incident commander review"],
    confidence: 0.9,
    human_review_required: true,
    safety_note: "Decision support only. Not connected to emergency services.",
    updated_at: "2026-05-09T10:20:00Z",
    evidence_count: 1,
  },
];

export const SEVERITY_STYLES: Record<Severity, { stroke: string; fill: string; badge: string; panel: string }> = {
  critical: {
    stroke: "#dc2626",
    fill: "#f87171",
    badge: "bg-red-500/20 text-red-200 border border-red-500/40",
    panel: "border-red-500/30 bg-red-500/10",
  },
  high: {
    stroke: "#ea580c",
    fill: "#fb923c",
    badge: "bg-orange-500/20 text-orange-100 border border-orange-400/40",
    panel: "border-orange-500/30 bg-orange-500/10",
  },
  medium: {
    stroke: "#ca8a04",
    fill: "#facc15",
    badge: "bg-yellow-400/20 text-yellow-100 border border-yellow-300/40",
    panel: "border-yellow-400/30 bg-yellow-400/10",
  },
  low: {
    stroke: "#16a34a",
    fill: "#4ade80",
    badge: "bg-emerald-500/20 text-emerald-100 border border-emerald-400/40",
    panel: "border-emerald-500/30 bg-emerald-500/10",
  },
};
